import Providers from '@/components/Providers'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { i18n } from '@/lib/locale/i18n-config'

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: { lang: string }
}) {
  return (
    <html lang={params.lang}>
      <body className="dark:bg-slate-800">
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
